### ISSUE TITLE
Pretrained models

### ISSUE THREAD

**Issue by simon-rob** [zsef123/MixNet-PyTorch#1]
@zsef123 Nice looking project.

Do you have any pretrained models available?

Many thanks

**Comment by ansleliu** [comment]
@simon-rob you can download all mixnet pre-trained weights from this repo.: [https://github.com/ansleliu/MixNet-Pytorch](https://github.com/ansleliu/MixNet-Pytorch)

**Comment by simon-rob** [comment]
@ansleliu many thanks
